### 상품 추가
POST http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN:

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
    ],
    "name": "나이키 에어포스"
}

### 상품 아이템 추가
POST http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN:

{
  "count": 1,
  "name": "270",
  "price": 100000,
  "productId": 1
}


### 상품 수정
PUT http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN:

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 100000
    }
    ],
    "id": 1,
    "name": "나이키 에어포스 한정판"
}


### 상품 아이템 수정
PUT http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN:

{
  "id": 1,
  "count": 1,
  "name": "260",
  "price": 100000
}



### 상품 삭제
DELETE http://localhost:8081/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN:


### 상품 아이템 삭제
DELETE http://localhost:8081/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN:



### 상품 검색
GET http://localhost:8081/search/product?name=나이키
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8081/search/product?detail?productId=1
Content-Type: application/json